---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: postgres
  namespace: data
spec:
  interval: 1m0s
  url: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres
  namespace: postgres
spec:
  chart:
    spec:
      chart: postgres
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: postgres
      version: 1.15.1
  interval: 10m0s
